package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/DISCARDING.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-amd64-cygwin/jdk8u291/1294/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Friday, April 9, 2021 12:03:37 AM PDT
*/

public interface DISCARDING
{

  /** Object adapter state that causes all requests to be discarded.
   */
  public static final short value = (short)(2);
}
